add code approval and code proposal in tx builder
archethic-foundation/libjs pull request #107
Opened 2023-02-07 10:31 UTC by tenmoves

add code approval and code proposal in tx builder.
changed the code of code approval and proposal to match the backend.

2023-02-08 09:30 UTC, bchamagne requested changes
Code is OK but here's a few more things to do:

- [ ] Add the case to unit test in test/transaction_builder.js
- [ ] Remove console.log
- [ ] run `npm run build` and commit the files changed in the dist

2023-02-20 16:02 UTC, bchamagne approved these changes

2023-02-21 03:51 UTC, apoorv-2204 approved these changes

2023-02-22 11:58 UTC, Neylix approved these changes

2023-02-22 12:03 UTC, merged