feat(crypto): Add encryption functionality
archethic-foundation/libjs pull request #196
Opened 2024-04-25 22:21 UTC by Rudy-Perrin

This pull request adds new encryption functionality to the crypto module. It includes the following commits:

- feat(crypto): getGenesisAddress

- feat(crypto): getServiceGenesisAddress

- feat(crypto): encryptSecret

- test(crypto): add test for encryptSecret

- refactor(crypto): improve imports, typing and JSDoc

It is necessary to do an `npm install` because the changes include updates to the `package.json` and `package-lock.json` files, as well as additions to the `crypto.test.ts` file.

2024-05-15 10:13 UTC, bchamagne requested changes
Hello Rudy, thanks again for a great PR. 
Do you mind if I directly commit a few things on this PR? 

Here's what I propose to change: 
- accept multiple public keys 
- add a decryptSecret function
- add a test to do a encryptSecret + decryptSecret and check input == output
- I'm not sure but I think we should restrain the secret to uint8array and not string (I need to run some tests)

2024-05-15 14:49 UTC, bchamagne commented on src/crypto.ts
> +}
```suggestion
/**
 * Encrypts a secret using a given public key
 * @param {string | Uint8Array} secret The secret to encrypt
 * @param {string | string[] | Uint8Array | Uint8Array[]} publicKeys The public keys authorized to decrypt the secret
 * @returns {{encryptedSecret: Uint8Array, authorizedKeys: AuthorizedKeyUserInput[]}}
 * @example
 * const storageNoncePublicKey = await archethic.network.getStorageNoncePublicKey();
 * const { encryptedSecret, authorizedKeys } = encryptSecret("something secret", storageNoncePublicKey);
 * const code = "" // The contract code
 * const tx = await archethic.transaction
 *  .new()
 *  .setType("contract")
 *  .setCode(code)
 *  .addOwnership(encryptedSecret, authorizedKeys)
 *  .build(seed, 0)
 *  .originSign(originPrivateKey)
 *  .send();
 */
export function encryptSecret(
  secret: string | Uint8Array,
  publicKeys: string | string[] | Uint8Array | Uint8Array[]
): { encryptedSecret: Uint8Array; authorizedKeys: AuthorizedKeyUserInput[] } {
  const publicKeysWrapped =
    typeof publicKeys == "string" || publicKeys instanceof Uint8Array ? [publicKeys] : publicKeys;

  const aesKey = randomSecretKey();
  const encryptedSecret = aesEncrypt(secret, aesKey);

  const authorizedKeys: AuthorizedKeyUserInput[] = publicKeysWrapped.map((publicKey) => {
    const encryptedAesKey = uint8ArrayToHex(ecEncrypt(aesKey, publicKey));
    return { encryptedSecretKey: encryptedAesKey, publicKey: maybeUint8ArrayToHex(publicKey) };
  });

  return { encryptedSecret, authorizedKeys };
}

/**
 * Decrypt a secret if authorized
 * @param {Uint8Array} encryptedSecret The secret to decrypt
 * @param {AuthorizedKeyUserInput[]} authorizedKeys The AES keys of authorized keys
 * @param {Keypair} keyPair The keyPair to use for decrypting
 * @returns {Uint8Array} The decrypted secret
 * @example
 * const keypair = deriveKeyPair("seed", 0);
 * const { encryptedSecret, authorizedKeys } = encryptSecret("something secret", keypair.publicKey);
 * const decryptedSecret = decryptSecret(encryptedSecret, authorizedKeys, keypair);
 */
export function decryptSecret(
  encryptedSecret: Uint8Array,
  authorizedKeys: AuthorizedKeyUserInput[],
  keyPair: Keypair
): Uint8Array {
  const publicKeyInHex = uint8ArrayToHex(keyPair.publicKey);

  const authorizedKey = authorizedKeys.find(({ publicKey: currentPubKey }) => currentPubKey == publicKeyInHex);
  if (!authorizedKey) throw new Error("This keypair is not authorized to decrypt the secret");

  const aesKey = ecDecrypt(authorizedKey.encryptedSecretKey, keyPair.privateKey);
  return aesDecrypt(encryptedSecret, aesKey);
}

```

2024-05-15 14:49 UTC, bchamagne commented on tests/crypto.test.ts
> +    });
```suggestion
  describe("encryptSecret / decryptSecret", () => {
    it("should encrypt a secret (string) using a public key and then decrypt it", () => {
      const keypair = deriveKeyPair("seed", 0);
      const secret = "mySecret";
      const result = encryptSecret(secret, keypair.publicKey);

      const secretDecrypted = decryptSecret(result.encryptedSecret, result.authorizedKeys, keypair);
      expect(new TextDecoder().decode(secretDecrypted)).toStrictEqual(secret);
    });

    it("should encrypt a secret (uint8array) using a public key and then decrypt it", () => {
      const keypair = deriveKeyPair("seed", 0);
      const secret = new TextEncoder().encode("mySecret");
      const result = encryptSecret(secret, keypair.publicKey);

      const secretDecrypted = decryptSecret(result.encryptedSecret, result.authorizedKeys, keypair);
      expect(secretDecrypted).toStrictEqual(secret);
    });

    it("should be able to be decrypted by anyone authorized", () => {
      const keypair1 = deriveKeyPair("seed", 0);
      const keypair2 = deriveKeyPair("seed2", 0);
      const secret = new TextEncoder().encode("mySecret");
      const result = encryptSecret(secret, [keypair1.publicKey, keypair2.publicKey]);

      const secretDecrypted1 = decryptSecret(result.encryptedSecret, result.authorizedKeys, keypair1);
      const secretDecrypted2 = decryptSecret(result.encryptedSecret, result.authorizedKeys, keypair2);
      expect(secretDecrypted1).toStrictEqual(secret);
      expect(secretDecrypted2).toStrictEqual(secret);
    });

    it("should not be able to be decrypted by non-authorized keys", () => {
      const keypair1 = deriveKeyPair("seed", 0);
      const keypair2 = deriveKeyPair("seed2", 0);
      const secret = "mySecret";
      const publicKey = uint8ArrayToHex(keypair1.publicKey);
      const result = encryptSecret(secret, [publicKey]);

      expect(() => {
        decryptSecret(result.encryptedSecret, result.authorizedKeys, keypair2);
      }).toThrow();
    });
```

2024-05-15 14:49 UTC, bchamagne commented on tests/crypto.test.ts
> +import { deriveKeyPair, ecDecrypt, ecEncrypt, isValidAddress, encryptSecret, hash, sign, verify } from "../src/crypto";
```suggestion
import {
  deriveKeyPair,
  ecDecrypt,
  ecEncrypt,
  isValidAddress,
  encryptSecret,
  hash,
  sign,
  verify,
  decryptSecret
} from "../src/crypto";
```

2024-05-15 14:56 UTC, bchamagne commented
By the way, I like what you did with JSDoc. I think we should generate the doc now.

<img width="1306" alt="Capture d’écran 2024-05-15 à 16 55 19" src="https://github.com/archethic-foundation/libjs/assets/74045243/96e9efcd-d196-4484-80b8-598434576d46">

2024-05-15 20:40 UTC, Rudy-Perrin commented
Yes I actually planned to use typedocs. #202

2024-05-27 07:55 UTC, bchamagne approved these changes
👍

2024-06-04 09:18 UTC, bchamagne commented on src/crypto.ts
> +  publicKeys: string | string[] | Uint8Array | Uint8Array[]
I like it as well but the devs must know about the spread operator. Is is common knowledge yet?

2024-06-07 07:56 UTC, bchamagne commented on src/crypto.ts
> +  publicKeys: string | string[] | Uint8Array | Uint8Array[]
@Rudy-Perrin what do you think?

2024-06-08 06:49 UTC, Rudy-Perrin commented on src/crypto.ts
> +  publicKeys: string | string[] | Uint8Array | Uint8Array[]
It's true that I never think about the spread operator, but I like it because it allows more flexibility.

2024-06-11 13:33 UTC, samuelmanzanera commented on src/crypto.ts
> +  publicKeys: string | string[] | Uint8Array | Uint8Array[]
Ok thanks, I made the change on 17acc4320db5b38951a38f9c876306c840224a12

2024-06-11 13:46 UTC, merged